spring:
  data:
    cassandra:
      request:
        consistency: local_quorum
        timeout: 30000
      contact-points: localhost
      port: 9042
      keyspace-name: mykeyspace
      local-datacenter: datacenter1
#importer no needed because we have defaults in the class
importer:
  accounts-uri: "/accounts"
  transactions-uri: "/transactions"
  login-uri: "/login"
  base-url: "http://localhost:8080"
  scheduler:
    cron: "0 0 1 * * ?"

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "docs-ui.html"

server:
  port: 8180
